export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";

export const START_PRODUCTS_DOWNLOAD = "START_PRODUCTS_DOWNLOAD";
export const PRODUCTS_DOWNLOAD_SUCCESS = "PRODUCTS_DOWNLOAD_SUCCESS";
export const PRODUCTS_DOWNLOAD_ERROR = "PRODUCTS_DOWNLOAD_ERROR";

export const GET_DELETE_PRODUCT = "GET_DELETE_PRODUCT";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_ERROR = "PRODUCT_DELETE_ERROR";

export const GET_EDIT_PRODUCT = "GET_EDIT_PRODUCT";
export const START_PRODUCT_EDITION = "START_PRODUCT_EDITION";
export const PRODUCT_EDIT_SUCCESS = "PRODUCT_EDIT_SUCCESS";
export const PRODUCT_EDIT_ERROR = "PRODUCT_EDIT_ERROR";

export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";
